# SPDX-FileCopyrightText: 2023 PeriHub <https://gitlab.com/dlr-perihub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  perihub_backend:
    image: perihub/backend:dev
    container_name: perihub_backend
    environment:
      - TRIAL=${TRIAL}
      - CLUSTER_URL=${CLUSTER_URL}
      - CLUSTER_USER=${CLUSTER_USER}
      - CLUSTER_JOB_PATH=${CLUSTER_JOB_PATH}
      - CLUSTER_PERILAB_PATH=${CLUSTER_PERILAB_PATH}
      - CLUSTER_PASSWORD=${CLUSTER_PASSWORD}
    volumes:
      - /mnt/ceph_data/filebrowser/users/hess_ja/perihub/peridigmJobs:/app/simulations
      - /mnt/ceph_data/filebrowser/users/hess_ja/perihub/rsaFiles:/app/rsaFiles
    networks:
      - web_network

  perihub_frontend:
    image: perihub/frontend:dev
    container_name: perihub_frontend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.perihub.entrypoints=websecure"
        - "traefik.http.routers.perihub.rule=Host(`perihub.nimbus.dlr.de`)"
        - "traefik.http.routers.perihub.tls=true"
        - "traefik.http.routers.perihub.service=perihub"
        - "traefik.http.services.perihub.loadbalancer.server.port=80"
        - "traefik.docker.network=proxy_l"
        - "enable.autoupdate.dockerhub=true"
    depends_on:
      - perihub_backend
    networks:
      - proxy_l
      - web_network

  perilab:
    image: perihub/perilab
    container_name: perihub_perilab
    volumes:
      - /mnt/ceph_data/filebrowser/users/hess_ja/perihub/peridigmJobs:/app/simulations
    networks:
      - web_network

networks:
  proxy_l:
    external: true
  web_network:
    driver: overlay
