version: '3'

services:
  modelgeneratorApi:
    build: api/.
    container_name: modelgeneratorApi
    image: modelgenerator_api_image
    ports:
      - 8000:80
    networks:
      - backend
    volumes:
      - model_generator_volume:/app/peridigmJobs

  modelgeneratorGui:
    build: gui/.
    container_name: modelgeneratorGui
    image: modelgenerator_gui_image
    ports:
      - 8080:80
    networks:
      - backend

  peridigm:
    build: 
      context: peridigm/.
      args: 
        GITLAB_USER: ${GITLAB_USER}
        GITLAB_TOKEN: ${GITLAB_TOKEN}
    container_name: peridigm
    image: peridigm_image
    # environment:
    #   GITLAB_USER: ${GITLAB_USER}
    #   GITLAB_TOKEN: ${GITLAB_TOKEN}
    # env_file:
    #   - .env
    ports:
      - 2222:22
    networks:
      - backend
    volumes:
      - model_generator_volume:/app/peridigmJobs
  
networks:
  backend:
    driver: bridge

volumes:
  model_generator_volume: