# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  perihub_backend:
    image: perihub/backend
    container_name: perihub_backend
    build:
      context: backend/.
      args:
        - CLUSTER_URL=${CLUSTER_URL}
    ports:
      - 8000:8000
    environment:
      - TRIAL=${TRIAL}
      - CLUSTER_URL=${CLUSTER_URL}
      - CLUSTER_USER=${CLUSTER_USER}
    volumes:
      - ${VOLUME}:/app/simulations
      - ${VOLUME}/rsaFiles:/app/rsaFiles

  perihub_frontend:
    image: perihub/frontend
    container_name: perihub_frontend
    build:
      context: frontend/.
      args:
        - TRIAL=${TRIAL}
        - KEYCLOAK_URL=${KEYCLOAK_URL}
        - REALM=${REALM}
        - CLIENT_ID=${CLIENT_ID}
        - CLUSTER_URL=${CLUSTER_URL}
    depends_on:
      - perihub_backend
    ports:
      - 8080:80

  perilab:
    image: perihub/perilab
    container_name: perihub_perilab
    ports:
      - 6000:80
      - 22:22
    volumes:
      - ${VOLUME}:/app/simulations
