version: '3'

services:
  cron:
    build: cron/.
    container_name: cron
    image: cron_image
    ports:
      - 6040:6040
    networks:
      - backend
  
networks:
  backend:
    driver: bridge