# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

services:
  perihub_backend:
    image: perihub/backend
    build:
      context: ./backend
    container_name: perihub_backend
    env_file:
      - .env
    volumes:
      - ${VOLUME}:/app/simulations
      - ${VOLUME}/rsaFiles:/app/rsaFiles

  perihub_frontend:
    image: perihub/frontend
    build:
      context: ./frontend
    container_name: perihub_frontend
    env_file:
      - .env
    depends_on:
      - perihub_backend
    ports:
      - 8080:80

  perilab:
    image: perihub/perilab
    container_name: perihub_perilab
    ports:
      - 22:22
    volumes:
      - ${VOLUME}:/app/simulations
