version: '3'

services:
  periHubApi:
    build:
      context: api/.
      args: 
        EXTERNAL: ${EXTERNAL}
        FASERVICES: ${FASERVICES}
    container_name:  perihub_periHubApi
    image: peri_hub_api_image
    ports:
      - 6020:80
    volumes:
      - /mnt/c/Users/hess_ja/Desktop/DockerProjects/periHubVolumes/peridigmJobs:/app/peridigmJobs
      - paraView_volume:/app/paraView
    networks:
      - backend

  periHubGui:
    build:
      context: gui/.
      args: 
        FASERVICES: ${FASERVICES}
    container_name:  perihub_periHubGui
    image: peri_hub_gui_image
    ports:
      - 6010:80
    networks:
      - backend

  peridigm:
    container_name:  perihub_peridigm
    image: harbor.fa-services.intra.dlr.de/hess_ja/peridigm_image
    ports:
      - 6030:80
    volumes:
      - /mnt/c/Users/hess_ja/Desktop/DockerProjects/periHubVolumes/peridigmJobs:/app/peridigmJobs
    networks:
      - backend

  paraview:
    build: 
      context: paraview/.
    container_name:  perihub_paraview
    image: paraview_image
    volumes:
      - paraView_volume:/app/paraView

  cron:
    build: cron/.
    container_name:  perihub_cron
    image: cron_image

volumes:
  paraView_volume:

networks:
  backend:
    driver: bridge