# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3.7"

services:
  perihub_backend:
    image: perihub/backend
    container_name: perihub_backend
    restart: unless-stopped
    volumes:
      - perihub:/app/simulations
    networks:
      - perihub_network
    environment:
      - TRIAL=${TRIAL}

  perihub_frontend:
    image: perihub/frontend
    container_name: perihub_frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.perihub.rule=Host(`perihub.nimbus-extern.dlr.de`)
      - traefik.http.routers.perihub.tls=true
      - traefik.http.routers.perihub.service=perihub
      - traefik.http.routers.perihub.entrypoints=dlrinternal
      - traefik.http.services.perihub.loadbalancer.server.port=80
      - traefik.docker.network=dlr-internal
    restart: unless-stopped
    depends_on:
      - perihub_backend
    networks:
      - perihub_network
      - dlr-internal
    environment:
      - TRIAL=${TRIAL}

  perilab:
    image: perihub/perilab
    container_name: perihub_perilab
    ports:
      - 6000:80
    volumes:
      - perihub:/app/simulations
    networks:
      - perihub_network

volumes:
  perihub:

networks:
  dlr-internal:
    external: true
  perihub_network:
    driver: bridge
