version: '3'

services:
  modelgeneratorApi:
    build: api/.
    container_name: modelgeneratorApi
    image: modelgenerator_api_image
    ports:
      - 8000:80
    networks:
      - backend

  modelgeneratorGui:
    build: gui/.
    container_name: modelgeneratorGui
    image: modelgenerator_gui_image
    ports:
      - 8080:80
    networks:
      - backend

  modelgeneratorEngineframe:
    build: engineframe/.
    container_name: modelgeneratorEngineframe
    image: modelgenerator_engineframe_image
    ports:
      - 8090:80
    networks:
      - backend
  
networks:
  backend:
    driver: bridge