# SPDX-FileCopyrightText: 2023 PeriHub <https://gitlab.com/dlr-perihub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  perihub_backend:
    image: perihub/backend
    build:
      context: backend/.
    container_name: perihub_backend
    ports:
      - 5000:5000
    environment:
      - DLR=${DLR}
      - TRIAL=${TRIAL}
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
      - ${VOLUME}rsaFiles:/app/rsaFiles
    networks:
      - web_network

  perihub_frontend:
    image: perihub/frontend
    build:
      context: frontend/.
    ports:
      - 8000:80
    environment:
      - DLR=${DLR}
      - TRIAL=${TRIAL}
    networks:
      - web_network

  perilab:
    container_name: perihub_perilab
    image: perihub/perilab
    ports:
      - 6000:80
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
