# SPDX-FileCopyrightText: 2023 PeriHub <https://gitlab.com/dlr-perihub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  perihub_backend:
    image: perihub/backend
    container_name: perihub_backend
    build:
      context: backend/.
    ports:
      - 5000:5000
    environment:
      - DLR=${DLR}
      - TRIAL=${TRIAL}
    volumes:
      - ${VOLUME}:/app/simulations

  perihub_frontend:
    image: perihub/frontend
    container_name: perihub_frontend
    build:
      context: frontend/.
    depends_on:
      - perihub_backend
    ports:
      - 8000:80
    environment:
      - DLR=${DLR}
      - TRIAL=${TRIAL}

  perilab:
    image: perihub/perilab
    container_name: perihub_perilab
    ports:
      - 6000:80
    volumes:
      - ${VOLUME}:/app/simulations
