version: '3'

services:
  modelgenerator:
    build: .
    container_name: modelgenerator
    image: modelgenerator_image
    ports:
      - 8000:80
    networks:
      - backend
  
networks:
  backend:
    driver: bridge