# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  periHubApi:
    build:
      context: backend/.
      args:
        DLR: ${DLR}
        DEV: ${DEV}
    container_name: perihub_periHubApi
    image: peri_hub_api_image
    ports:
      - 6020:80
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
      - ${VOLUME}rsaFiles:/app/rsaFiles
    networks:
      - backend

  periHubGui:
    build:
      context: frontend/.
      args:
        DLR: ${DLR}
        DEV: ${DEV}
    container_name: perihub_periHubGui
    image: peri_hub_gui_image
    ports:
      - 6010:80
    networks:
      - backend

  peridigm:
    container_name: perihub_peridigm
    image: perihub/peridigm
    ports:
      - 6030:80
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
    networks:
      - backend

  paraview:
    build:
      context: paraview/.
    container_name: perihub_paraview
    image: paraview_image
    volumes:
      - paraView_volume:/app/paraView

  trame:
    build:
      context: trame/.
      args:
        DEV: ${DEV}
    container_name: perihub_trame
    image: trame_image
    ports:
      - 6040:80
      - 6041:6041
      - 6042:6042
      - 6043:6043
      - 6044:6044
      - 6045:6045
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
      - paraView_volume:/app/paraView

volumes:
  paraView_volume:


networks:
  backend:
    driver: bridge
