# SPDX-FileCopyrightText: 2023 PeriHub <https://gitlab.com/dlr-perihub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  periHubBackend:
    image: perihub/backend
    container_name: perihub_backend
    ports:
      - 6020:80
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
      - ${VOLUME}rsaFiles:/app/rsaFiles
    networks:
      - backend

  periHubFrontend:
    image: perihub/frontend
    ports:
      - 6010:80
    networks:
      - backend

  perilab:
    container_name: perihub_perilab
    image: perihub/perilab
    ports:
      - 6040:80
    volumes:
      - ${VOLUME}peridigmJobs:/app/peridigmJobs
    networks:
      - backend

networks:
  backend:
    driver: bridge
