# SPDX-FileCopyrightText: 2023 PeriHub <https://gitlab.com/dlr-perihub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

version: "3"

services:
  perihub_backend:
    image: perihub/backend
    restart: unless-stopped
    volumes:
      - perihub:/app/simulations
    networks:
      - web_network

  perihub_frontend:
    image: perihub/frontend
    labels:
      - traefik.enable=true
      - "traefik.constraint-label=traefik-public"
      - traefik.http.routers.perilab-results.rule=Host(`perihub.nimbus-extern.dlr.de`)
      - traefik.http.routers.perihub.tls=true
      - traefik.http.routers.perihub.service=perihub
      - "traefik.http.routers.perihub.entrypoints=dlrinternal"
      - traefik.http.services.perihub.loadbalancer.server.port=80
      - traefik.docker.network=dlr-internal
    networks:
      - web_network
      - dlr-internal

  perilab:
    image: perihub/perilab
    ports:
      - 6000:80
    volumes:
      - perihub:/app/simulations

volumes:
  perihub:

networks:
  dlr-internal:
    external: true
  web_network:
    driver: bridge
