# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "perihub"
version = "4.0.0"
description = "PeriHub"
license = "Apache-2.0"
authors = ["Jan-Timo Hesse"]
readme = "README.md"
repository = "https://github.com/PeriHub/PeriHub"
keywords = ["perihub","perilab","peridynamics"]

[tool.coverage.run]
branch = true

[tool.coverage.html]
directory = "build/htmlcov"

[tool.black]
line-length = 120
target-version = ['py311']
include = '\.pyi?$'

[tool.isort]
line_length = 120
skip = "doc"
profile = 'black'

[tool.pytest.ini_options]
pythonpath = "."

[tool.flake8]
max-line-length = 120
