# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

name: 🐜 Bug report
description: If something isn't working 🔧
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: perilab-version
    attributes:
      label: PeriHub Version
      description: What version of PeriHub are you using?
      placeholder: 2.2
    validations:
      required: true
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: 3.10
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      value: "The simulation should..."
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What is the actual behavior?
      value: "My simulation errored..."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell
  - type: checkboxes
    id: operating-systems
    attributes:
      label: Which release of PeriHub are you seeing the problem on?
      description: You may select more than one.
      options:
        - label: Linux Release
        - label: Docker Image
