// SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub>
//
// SPDX-License-Identifier: Apache-2.0

/* eslint-disable */
// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import "quasar/dist/types/feature-flag";

declare module "quasar/dist/types/feature-flag" {
  interface QuasarFeatureFlags {
    store: true;
  }
}
