// This file is auto-generated by @hey-api/openapi-ts

export type Adapt = {
    stableStepDifference?: number;
    maximumBondDifference?: number;
    stableBondDifference?: number;
};

export type AdditiveModel = {
    additiveModelId?: number | null;
    name: string;
    additiveType: string;
    printTemp: number;
};

/**
 * One @analysis function of a model (GET /models/{name}/analyses).
 */
export type AnalysisInfo = {
    id: string;
    label: string;
    params: Array<Valve>;
};

export type AnalysisRequest = {
    data: ModelData;
    valves: Valves;
    analysis_params?: {
        [key: string]: (number | boolean | string);
    };
};

export type AuthorizationUrlResponse = {
    authorization_url: string;
    state: string;
};

export type Block = {
    blocksId: number;
    name: string;
    material?: string | null;
    damageModel?: string | null;
    thermalModel?: string | null;
    additiveModel?: string | null;
    horizon?: number | null;
    density?: number | null;
    specificHeatCapacity?: number | string | null;
    show?: boolean | null;
};

export type BlockFunction = {
    id: number;
    function: string;
};

export type Body_generate_model = {
    data: ModelData;
    valves: Valves;
};

export type Body_preview_model = {
    data: ModelData;
    valves: Valves;
    /**
     * Unsaved YAML model text (editor preview)
     */
    source?: string | null;
};

export type Body_save_model_file = {
    source_code: string;
};

export type Body_upload_files = {
    files: Array<((Blob | File))>;
};

export type BondFilters = {
    bondFiltersId?: number | null;
    name: string;
    type: string;
    allow_contact?: boolean | null;
    normalX: number;
    normalY: number;
    normalZ: number;
    lowerLeftCornerX?: number | null;
    lowerLeftCornerY?: number | null;
    lowerLeftCornerZ?: number | null;
    bottomUnitVectorX?: number | null;
    bottomUnitVectorY?: number | null;
    bottomUnitVectorZ?: number | null;
    bottomLength?: number | null;
    sideLength?: number | null;
    centerX?: number | null;
    centerY?: number | null;
    centerZ?: number | null;
    radius?: number | null;
    show?: boolean | null;
};

export type BoundaryCondition = {
    conditionsId?: number | null;
    stepId?: Array<(number)> | null;
    name: string;
    nodeSet?: number | null;
    boundarytype: string;
    variable: string;
    blockId?: number | null;
    coordinate: string;
    value: string;
};

export type BoundaryConditions = {
    conditions: Array<BoundaryCondition>;
};

export type Compute = {
    computesId?: number | null;
    computeClass: string;
    name: string;
    variable: string;
    equation?: string | null;
    calculationType?: string | null;
    blockName?: string | null;
    nodeSetId?: number | null;
    xValue?: number | null;
    yValue?: number | null;
    zValue?: number | null;
};

export type Contact = {
    contactModels?: Array<ContactModel> | null;
    searchFrequency?: number | null;
    onlySurfaceContactNodes?: boolean | null;
};

export type ContactGroup = {
    contactGroupId?: number | null;
    name: string;
    masterBlockId: number;
    slaveBlockId: number;
    searchRadius: number;
};

export type ContactModel = {
    contactModelId?: number | null;
    name: string;
    contactType: string;
    contactRadius: number;
    contactStiffness: number;
    contactGroups: Array<ContactGroup>;
};

export type CriticalEnergyCalc = {
    calculateCriticalEnergy?: boolean | null;
    k1c?: number | null;
};

export type Damage = {
    damagesId?: number | null;
    name: string;
    damageModel: string;
    criticalStretch?: number | null;
    criticalVonMisesStress?: number | null;
    criticalDamage?: number | null;
    thresholdDamage?: number | null;
    criticalDamageToNeglect?: number | null;
    criticalEnergy?: number | null;
    criticalEnergyCalc?: CriticalEnergyCalc | null;
    interBlockDamage?: boolean | null;
    numberOfBlocks?: number | null;
    interBlocks?: Array<InterBlock> | null;
    anistropicDamage?: boolean | null;
    anistropicDamageX?: number | null;
    anistropicDamageY?: number | null;
    anistropicDamageZ?: number | null;
    onlyTension?: boolean | null;
    thickness?: number | null;
};

export type Deviations = {
    enabled: boolean;
    fileInput?: boolean | null;
    sampleSize: number;
    parameters: Array<Parameter>;
    oldParameters?: Array<OldParameter> | null;
    file?: string | null;
    mean?: number | null;
    std?: number | null;
};

export type Discretization = {
    distributionType: string;
    discType?: string | null;
    gcode?: Gcode | null;
    nodeSets?: Array<NodeSet> | null;
};

export type EngineeringConstants = {
    E1?: number | null;
    E2?: number | null;
    E3?: number | null;
    G12?: number | null;
    G13?: number | null;
    G23?: number | null;
    nu12?: number | null;
    nu13?: number | null;
    nu23?: number | null;
};

export type Gcode = {
    overwriteMesh: boolean;
    sampling: number;
    width: number;
    height: number;
    scale: number;
    blockFunctions?: Array<BlockFunction> | null;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InterBlock = {
    interBlockid?: number | null;
    firstBlockId: number;
    secondBlockId: number;
    value: number;
};

export type Job = {
    verbose: boolean;
    tasks?: number | null;
};

export type LibraryItemIn = {
    name: string;
    visibility?: 'private' | 'team' | 'org' | 'public';
    tags?: Array<(string)>;
    team_id?: string | null;
    project_id?: string | null;
    description?: string | null;
    config?: {
    [key: string]: unknown;
} | null;
    properties?: {
    [key: string]: unknown;
} | null;
    source?: string | null;
};

export type visibility = 'private' | 'team' | 'org' | 'public';

export type LibraryItemOut = {
    id: string;
    owner_id: string;
    org_id: string | null;
    team_id: string | null;
    project_id: string | null;
    name: string;
    visibility: string;
    tags: Array<(string)>;
    description?: string | null;
    config?: {
    [key: string]: unknown;
} | null;
    properties?: {
    [key: string]: unknown;
} | null;
    source?: string | null;
};

/**
 * Current entitlement grant - see support/license_client.py and
 * support/entitlements.py.
 */
export type LicenseStatus = {
    plan: string;
    features: Array<(string)>;
    seats?: number | null;
    expires_at?: string | null;
    source: string;
    license_server_configured: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type Material = {
    materialsId?: number | null;
    name: string;
    matType: Array<(string)>;
    bulkModulus?: number | null;
    shearModulus?: number | null;
    shearModulusXY?: number | null;
    shearModulusYZ?: number | null;
    shearModulusXZ?: number | null;
    youngsModulus?: number | null;
    youngsModulusX?: number | null;
    youngsModulusY?: number | null;
    youngsModulusZ?: number | null;
    poissonsRatio?: number | null;
    poissonsRatioXY?: number | null;
    poissonsRatioYZ?: number | null;
    poissonsRatioXZ?: number | null;
    planeStress: boolean;
    planeStrain: boolean;
    materialSymmetry: string;
    stabilizationType: string;
    hourglassCoefficient: number;
    actualHorizon?: number | null;
    yieldStress?: number | null;
    stiffnessMatrix?: StiffnessMatrix | null;
    properties: Array<properties> | null;
    numStateVars?: number | null;
    computePartialStress?: boolean | null;
    useCollocationNodes?: boolean | null;
};

export type Matrix = {
    C11?: number | null;
    C12?: number | null;
    C13?: number | null;
    C14?: number | null;
    C15?: number | null;
    C16?: number | null;
    C22?: number | null;
    C23?: number | null;
    C24?: number | null;
    C25?: number | null;
    C26?: number | null;
    C33?: number | null;
    C34?: number | null;
    C35?: number | null;
    C36?: number | null;
    C44?: number | null;
    C45?: number | null;
    C46?: number | null;
    C55?: number | null;
    C56?: number | null;
    C66?: number | null;
};

export type MeResponse = {
    user_id: string;
    email: string | null;
    display_name: string;
    role: string;
    auth_provider: string;
    org_id: string | null;
};

export type MemberIn = {
    user_id: string;
    role?: string;
};

export type MemberOut = {
    user_id: string;
    role: string;
};

export type Model = {
    modelFolderName: string;
    meshSource?: 'model' | 'upload';
    twoDimensional: boolean;
    horizon?: number | null;
    meshFile?: string | null;
};

export type meshSource = 'model' | 'upload';

export type ModelData = {
    additive?: Array<AdditiveModel> | null;
    blocks: Array<Block>;
    bondFilters?: Array<BondFilters> | null;
    boundaryConditions: BoundaryConditions;
    computes?: Array<Compute> | null;
    contact?: Contact | null;
    damages?: Array<Damage> | null;
    discretization?: Discretization | null;
    deviations?: Deviations | null;
    job: Job;
    materials?: Array<Material> | null;
    model: Model;
    outputs: Array<Output>;
    preCalculations?: PreCalculations | null;
    solvers: Array<Solver>;
    thermal?: Array<ThermalModel> | null;
};

export type NodeSet = {
    nodeSetId?: number | null;
    file: string;
};

export type OldParameter = {
    parameterId?: number | null;
    id: Array<(string)>;
    factor: number;
};

export type Output = {
    outputsId?: number | null;
    name: string;
    selectedFileType?: string | null;
    selectedOutputs?: Array<(string)> | null;
    Write_After_Damage?: boolean | null;
    Frequency?: number | null;
    numberOfOutputSteps?: number | null;
    useOutputFrequency?: boolean | null;
    InitStep: number;
};

export type Parameter = {
    parameterId?: number | null;
    id: Array<(string)>;
    std: number;
};

export type PointData = {
    points: Array<(number)>;
    block_ids: Array<(number)>;
    dx_value: number;
};

export type PointDataResults = {
    nodes: Array<(number)>;
    value: Array<(number)>;
    variables: Array<(string)>;
    number_of_steps: number;
    min_value: number;
    max_value: number;
    time: number;
};

export type PreCalculations = {
    deformedBondGeometry?: boolean | null;
    deformationGradient?: boolean | null;
    shapeTensor?: boolean | null;
    bondAssociatedShapeTensor?: boolean | null;
    bondAssociateDeformationGradient?: boolean | null;
};

export type PreviewBlock = {
    id: number;
    bounds: {
        [key: string]: (number);
    };
    labelX: number;
    labelY: number;
};

export type PreviewResponse = {
    x: Array<(number)>;
    y: Array<(number)>;
    z: Array<(number)>;
    block: Array<(number)>;
    bounds_min: Array<(number)>;
    bounds_max: Array<(number)>;
    shapes?: Array<{
        [key: string]: unknown;
    }>;
    blocks?: Array<PreviewBlock>;
    regions?: {
    [key: string]: unknown;
} | null;
};

export type ProjectIn = {
    name: string;
    description?: string | null;
};

export type ProjectOut = {
    id: string;
    org_id: string;
    name: string;
    description: string | null;
    created_by: string;
};

/**
 * Full status of a single run, keyed by its own id (JobQueueEntry.id -
 * stable for the life of the run, independent of how many times its
 * model_name/model_folder_name has been resubmitted before or since).
 * This is the authoritative per-run detail; Status/Jobs only carry a
 * same-shaped snapshot of the latest run for quick folder-level display.
 */
export type RunStatus = {
    id: string;
    model_name: string;
    model_folder_name: string;
    status: string;
    perilab_job_id?: string | null;
    submitted_at?: string | null;
    started_at?: string | null;
    finished_at?: string | null;
    error?: string | null;
    results?: boolean;
    csvResults?: boolean;
    progress?: number | null;
    currentStep?: number | null;
    totalSteps?: number | null;
    model?: {
    [key: string]: unknown;
} | null;
};

export type SignupRequest = {
    email: string;
    password: string;
    display_name: string;
};

export type Solver = {
    solverId?: number | null;
    name?: string | null;
    stepId?: number;
    matEnabled?: boolean;
    damEnabled?: boolean | null;
    dispEnabled?: boolean | null;
    tempEnabled?: boolean | null;
    addEnabled?: boolean | null;
    initialTime?: number | null;
    finalTime?: number | null;
    additionalTime?: number | null;
    fixedDt?: number | null;
    solvertype: string;
    safetyFactor: number;
    verlet?: Verlet | null;
    static?: Static | null;
    stopAfterDamageInitation?: boolean | null;
    endStepAfterDamage?: number | null;
    stopAfterCertainDamage?: boolean | null;
    maximumDamage?: number | null;
    stopBeforeDamageInitation?: boolean | null;
    adaptivetimeStepping?: boolean | null;
    adapt?: Adapt | null;
    calculateCauchy?: boolean | null;
    calculateVonMises?: boolean | null;
    calculateStrain?: boolean | null;
};

export type Static = {
    numberOfSteps: number;
    maximumNumberOfIterations?: number | null;
    NLsolver?: boolean | null;
    showSolverIteration?: boolean | null;
    residualTolerance?: number | null;
    solutionTolerance?: number | null;
    linearStartValue?: Array<(number)> | null;
    residualScaling?: number | null;
    m?: number | null;
};

/**
 * Folder-level summary: model-config existence plus a snapshot of the
 * *most recently submitted* run for this model_name/model_folder_name.
 * A folder can have more than one run over time (re-submissions) - use
 * `run_id` with GET /jobs/{run_id} for authoritative detail on that
 * specific run, or GET /jobs/{model_name}/{model_folder_name}/runs for
 * the full history, rather than assuming this is "the" run.
 */
export type Status = {
    created?: boolean | null;
    submitted?: boolean | null;
    results?: boolean | null;
    csvResults?: boolean | null;
    meshfileExist?: boolean | null;
    progress?: number | null;
    currentStep?: number | null;
    totalSteps?: number | null;
    run_id?: string | null;
};

export type StiffnessMatrix = {
    calculateStiffnessMatrix?: boolean | null;
    engineeringConstants: EngineeringConstants;
    matrix: Matrix;
};

export type TeamIn = {
    name: string;
};

export type TeamOut = {
    id: string;
    org_id: string;
    name: string;
};

export type ThermalModel = {
    thermalModelsId?: number | null;
    name: string;
    thermalModel: Array<(string)>;
    thermalType: string;
    heatTransferCoefficient?: number | null;
    environmentalTemperature?: number | null;
    requiredSpecificVolume?: number | null;
    thermalConductivity?: number | null;
    thermalExpansionCoefficient?: number | null;
    thermalConductivityPrintBed?: number | null;
    printBedTemperature?: number | null;
    printBedZCoord?: number | null;
    file?: string | null;
    numStateVars?: number | null;
    predefinedFieldNames?: string | null;
};

export type TrialIdResponse = {
    username: string;
};

/**
 * Aggregate usage stats - see routers/usage.py.
 */
export type UsageSummary = {
    total_jobs_submitted?: number;
    total_jobs_cancelled?: number;
    jobs_per_user?: {
        [key: string]: (number);
    };
    jobs_per_model?: {
        [key: string]: (number);
    };
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type Valve = {
    name: string;
    type: 'text' | 'number' | 'select' | 'checkbox' | 'data';
    value: number | boolean | string;
    value_type: 'int' | 'float' | 'bool' | 'str';
    label: string;
    description: string;
    options?: Array<(string)> | string | null;
    depends?: string | null;
};

export type type = 'text' | 'number' | 'select' | 'checkbox' | 'data';

export type value_type = 'int' | 'float' | 'bool' | 'str';

export type Valves = {
    valves: Array<Valve>;
};

export type Verlet = {
    numericalDamping?: number | null;
    outputFrequency?: number;
};

export type VersionData = {
    current: string;
    latest: string;
    perilab_current: string;
    perilab_latest: string;
};

export type app__routers__oauth__AuthResponse = {
    token: string;
    user_id: string;
    display_name: string;
    role: string;
};

export type properties = {
    materialsPropId?: number | null;
    name: string;
    value?: number | null;
};

export type GenerateModelData = {
    modelFolderName: string;
    modelName: string;
    requestBody: Body_generate_model;
};

export type GenerateModelResponse = unknown;

export type PreviewModelData = {
    modelName: string;
    requestBody: Body_preview_model;
};

export type PreviewModelResponse = PreviewResponse;

export type GetModelsData = {
    ownOnly?: boolean;
    verify?: boolean;
};

export type GetModelsResponse = Array<{
    [key: string]: unknown;
}>;

export type AddModelData = {
    description: string;
    modelFormat?: 'yaml' | 'python';
    modelName: string;
};

export type AddModelResponse = string;

export type GetValvesData = {
    modelName: string;
};

export type GetValvesResponse = Valves;

export type GetAnalysesData = {
    modelName: string;
};

export type GetAnalysesResponse = Array<AnalysisInfo>;

export type GetConfigData = {
    modelName: string;
};

export type GetConfigResponse = unknown;

export type SaveConfigData = {
    modelName: string;
    requestBody: ModelData;
};

export type SaveConfigResponse = unknown;

export type GetModelData = {
    modelFolderName: string;
    modelName: string;
};

export type GetModelResponse = unknown;

export type GetPointDataData = {
    meshFile?: string | null;
    modelFolderName: string;
    modelName: string;
    twoD?: boolean | null;
};

export type GetPointDataResponse = PointData;

export type GetWorkspaceFileData = {
    filename: string;
    modelFolderName: string;
    modelName: string;
};

export type GetWorkspaceFileResponse = unknown;

export type ViewInputFileData = {
    modelFolderName: string;
    modelName: string;
};

export type ViewInputFileResponse = string;

export type WriteInputFileData = {
    inputString: string;
    modelFolderName: string;
    modelName: string;
};

export type WriteInputFileResponse = unknown;

export type GetOwnModelFileData = {
    modelName: string;
    part?: 'model' | 'analysis';
};

export type GetOwnModelFileResponse = string;

export type SaveModelFileData = {
    modelName: string;
    part?: 'model' | 'analysis';
    requestBody: Body_save_model_file;
};

export type SaveModelFileResponse = unknown;

export type DeleteModelFileData = {
    modelName: string;
};

export type DeleteModelFileResponse = unknown;

export type UploadFilesData = {
    formData: Body_upload_files;
    modelFolderName: string;
    modelName: string;
};

export type UploadFilesResponse = string;

export type RunModelData = {
    jobIds?: string | null;
    modelFolderName?: string;
    modelName?: string;
    requestBody: ModelData;
    verbose?: boolean;
};

export type RunModelResponse = unknown;

export type GetJobFoldersData = {
    modelName: string;
};

export type GetJobFoldersResponse = Array<(string)>;

export type GetStatusData = {
    meshfile?: string | null;
    modelFolderName: string;
    modelName: string;
};

export type GetStatusResponse = Status;

export type ListAllRunsResponse = Array<RunStatus>;

export type StreamRunLogData = {
    debug?: boolean;
    runId: string;
};

export type StreamRunLogResponse = unknown;

export type DeleteRunData = {
    runId: string;
};

export type DeleteRunResponse = unknown;

export type CancelRunData = {
    runId: string;
};

export type CancelRunResponse = unknown;

export type RunAnalysisData = {
    analysisId: string;
    modelFolderName?: string;
    modelName: string;
    requestBody: AnalysisRequest;
    runId?: string | null;
};

export type RunAnalysisResponse = unknown;

export type GetPlotData = {
    deviationsEnabled?: boolean;
    modelFolderName?: string;
    modelName?: string;
    output?: string;
    runId?: string | null;
};

export type GetPlotResponse = unknown;

export type GetResultsData = {
    allData?: boolean;
    modelFolderName?: string;
    modelName?: string;
    output?: string;
    runId?: string | null;
};

export type GetResultsResponse = unknown;

export type GetPointDataResultsData = {
    axis?: string;
    colorBarMax?: number | null;
    colorBarMin?: number | null;
    displFactor?: number;
    filter?: string;
    modelFolderName?: string;
    modelName?: string;
    output?: string;
    runId?: string | null;
    step?: number;
    variable?: string;
};

export type GetPointDataResultsResponse = PointDataResults;

export type DeleteModelData = {
    modelFolderName: string;
    modelName: string;
};

export type DeleteModelResponse = unknown;

export type DeleteUserDataResponse = unknown;

export type DeleteStaleUserDataData = {
    days?: number | null;
};

export type DeleteStaleUserDataResponse = unknown;

export type GetPublicationsResponse = string;

export type GetPrognosisEnergyResponse = {
    [key: string]: unknown;
};

export type GetCurrentEnergyResponse = number;

export type GetMyUsageResponse = UsageSummary;

export type GetAllUsageResponse = UsageSummary;

export type GetLicenseStatusResponse = LicenseStatus;

export type RefreshLicenseResponse = LicenseStatus;

export type GetTrialIdResponse = TrialIdResponse;

export type SignupData = {
    requestBody: SignupRequest;
};

export type SignupResponse = app__routers__oauth__AuthResponse;

export type LoginData = {
    requestBody: LoginRequest;
};

export type LoginResponse = app__routers__oauth__AuthResponse;

export type GetCurrentUserInfoResponse = MeResponse;

export type StartOidcLoginResponse = AuthorizationUrlResponse;

export type OidcCallbackData = {
    code: string;
};

export type OidcCallbackResponse = app__routers__oauth__AuthResponse;

export type ListLibraryItemsData = {
    kind: 'model-config' | 'material';
    projectId?: string | null;
    /**
     * Case-insensitive substring match on name
     */
    search?: string | null;
    /**
     * Exact tag match
     */
    tag?: string | null;
};

export type ListLibraryItemsResponse = Array<LibraryItemOut>;

export type CreateLibraryItemData = {
    kind: 'model-config' | 'material';
    requestBody: LibraryItemIn;
};

export type CreateLibraryItemResponse = LibraryItemOut;

export type UpdateLibraryItemData = {
    itemId: string;
    kind: 'model-config' | 'material';
    requestBody: LibraryItemIn;
};

export type UpdateLibraryItemResponse = LibraryItemOut;

export type DeleteLibraryItemData = {
    itemId: string;
    kind: 'model-config' | 'material';
};

export type DeleteLibraryItemResponse = unknown;

export type ListProjectsResponse = Array<ProjectOut>;

export type CreateProjectData = {
    requestBody: ProjectIn;
};

export type CreateProjectResponse = ProjectOut;

export type ListProjectMembersData = {
    projectId: string;
};

export type ListProjectMembersResponse = Array<MemberOut>;

export type AddProjectMemberData = {
    projectId: string;
    requestBody: MemberIn;
};

export type AddProjectMemberResponse = MemberOut;

export type RemoveProjectMemberData = {
    projectId: string;
    userId: string;
};

export type RemoveProjectMemberResponse = unknown;

export type ListTeamsResponse = Array<TeamOut>;

export type CreateTeamData = {
    requestBody: TeamIn;
};

export type CreateTeamResponse = TeamOut;

export type AddTeamMemberData = {
    teamId: string;
    userId: string;
};

export type AddTeamMemberResponse = unknown;

export type RemoveTeamMemberData = {
    teamId: string;
    userId: string;
};

export type RemoveTeamMemberResponse = unknown;

export type GetPublicConfigResponse = {
    [key: string]: unknown;
};

export type HealthcheckHealthGetResponse = unknown;

export type GetVersionResponse = VersionData;

export type $OpenApiTs = {
    '/workspaces/{model_name}/{model_folder_name}/generate': {
        post: {
            req: GenerateModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}/preview': {
        post: {
            req: PreviewModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: PreviewResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models': {
        get: {
            req: GetModelsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<{
                    [key: string]: unknown;
                }>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: AddModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}/params': {
        get: {
            req: GetValvesData;
            res: {
                /**
                 * Successful Response
                 */
                200: Valves;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}/analyses': {
        get: {
            req: GetAnalysesData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<AnalysisInfo>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}/config': {
        get: {
            req: GetConfigData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: SaveConfigData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/download': {
        get: {
            req: GetModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/points': {
        get: {
            req: GetPointDataData;
            res: {
                /**
                 * Successful Response
                 */
                200: PointData;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/files/{filename}': {
        get: {
            req: GetWorkspaceFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/input-deck': {
        get: {
            req: ViewInputFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: WriteInputFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}/source': {
        get: {
            req: GetOwnModelFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        put: {
            req: SaveModelFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/models/{model_name}': {
        delete: {
            req: DeleteModelFileData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/files': {
        post: {
            req: UploadFilesData;
            res: {
                /**
                 * Successful Response
                 */
                200: string;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/jobs': {
        post: {
            req: RunModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}': {
        get: {
            req: GetJobFoldersData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<(string)>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}/status': {
        get: {
            req: GetStatusData;
            res: {
                /**
                 * Successful Response
                 */
                200: Status;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/jobs/runs': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<RunStatus>;
            };
        };
    };
    '/jobs/{run_id}/log/stream': {
        get: {
            req: StreamRunLogData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/jobs/{run_id}': {
        delete: {
            req: DeleteRunData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/jobs/{run_id}/cancel': {
        put: {
            req: CancelRunData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/results/analysis': {
        post: {
            req: RunAnalysisData;
            res: {
                /**
                 * The analysis image
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/results/plot': {
        get: {
            req: GetPlotData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/results/download': {
        get: {
            req: GetResultsData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/results/points': {
        get: {
            req: GetPointDataResultsData;
            res: {
                /**
                 * Successful Response
                 */
                200: PointDataResults;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/workspaces/{model_name}/{model_folder_name}': {
        delete: {
            req: DeleteModelData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/users/me/data': {
        delete: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/admin/user-data': {
        delete: {
            req: DeleteStaleUserDataData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/publications': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: string;
            };
        };
    };
    '/energy/prognosis': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/energy/current': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: number;
            };
        };
    };
    '/usage/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UsageSummary;
            };
        };
    };
    '/usage/all': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UsageSummary;
            };
        };
    };
    '/license/status': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: LicenseStatus;
            };
        };
    };
    '/license/refresh': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: LicenseStatus;
            };
        };
    };
    '/auth/trial-id': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: TrialIdResponse;
            };
        };
    };
    '/auth/signup': {
        post: {
            req: SignupData;
            res: {
                /**
                 * Successful Response
                 */
                200: app__routers__oauth__AuthResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/login': {
        post: {
            req: LoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: app__routers__oauth__AuthResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/auth/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: MeResponse;
            };
        };
    };
    '/oauth/oidc/login': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: AuthorizationUrlResponse;
            };
        };
    };
    '/oauth/oidc/callback': {
        get: {
            req: OidcCallbackData;
            res: {
                /**
                 * Successful Response
                 */
                200: app__routers__oauth__AuthResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/library/{kind}': {
        get: {
            req: ListLibraryItemsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<LibraryItemOut>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CreateLibraryItemData;
            res: {
                /**
                 * Successful Response
                 */
                200: LibraryItemOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/library/{kind}/{item_id}': {
        put: {
            req: UpdateLibraryItemData;
            res: {
                /**
                 * Successful Response
                 */
                200: LibraryItemOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteLibraryItemData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/projects': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ProjectOut>;
            };
        };
        post: {
            req: CreateProjectData;
            res: {
                /**
                 * Successful Response
                 */
                200: ProjectOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/projects/{project_id}/members': {
        get: {
            req: ListProjectMembersData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<MemberOut>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: AddProjectMemberData;
            res: {
                /**
                 * Successful Response
                 */
                200: MemberOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/projects/{project_id}/members/{user_id}': {
        delete: {
            req: RemoveProjectMemberData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/teams': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<TeamOut>;
            };
        };
        post: {
            req: CreateTeamData;
            res: {
                /**
                 * Successful Response
                 */
                200: TeamOut;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/teams/{team_id}/members/{user_id}': {
        post: {
            req: AddTeamMemberData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: RemoveTeamMemberData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/config/public': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: {
                    [key: string]: unknown;
                };
            };
        };
    };
    '/health': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/version': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: VersionData;
            };
        };
    };
};