title: PeriHub
description: PeriHub is a powerful software solution that can significantly benefit research in various fields. It is an extension of the open-source PeriLab software, providing a numerical implementation of the peridynamic theory. With PeriHub, researchers gain access to a valuable tool for addressing specific challenges and exploring diverse use cases in materials science, engineering, and related disciplines.
theme: just-the-docs

url: https://PeriHub.github.io/PeriHub

aux_links:
  Template Repository: https://github.com//PeriHub/PeriHub
