# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

name: app

channels:
  - conda-forge
  - anaconda
  # - dlr-sc

dependencies:
  # - pythonocc-core
  - yaml
  - python=3.8
  - conda-build
  - pip:
      - -r file:requirements.txt
      - pyyaml
      - openturns
