# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

name: deploy
on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches: [main]
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t perihub/backend ./backend
      - name: Build Docker image
        run: docker build -t perihub/frontend ./frontend
      - name: Publish to Registry
        run: docker push perihub/backend
      - name: Publish to Registry
        run: docker push perihub/frontend
