# SPDX-FileCopyrightText: 2023 PeriHub <https://github.com/PeriHub/PeriHub>
#
# SPDX-License-Identifier: Apache-2.0

name: Deploy
on:
  push:
    tags: ["v[0-9].[0-9]+.[0-9]+"]
  workflow_dispatch:
jobs:
  build:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get version from Project.toml
        id: get_version
        run: echo "PERIHUB_VERSION=$(awk -F'"' '/version/{print $2}' backend/app/pyproject.toml)" >> $GITHUB_OUTPUT
      - name: Build Docker image
        run: docker build -t perihub/backend:${{ steps.get_version.outputs.PERIHUB_VERSION }} ./backend
      - name: Build Docker image
        run: docker build -t perihub/frontend:${{ steps.get_version.outputs.PERIHUB_VERSION }} ./frontend
      - name: Publish to Registry
        run: docker push perihub/backend:${{ steps.get_version.outputs.PERIHUB_VERSION }}
      - name: Publish to Registry
        run: docker push perihub/frontend:${{ steps.get_version.outputs.PERIHUB_VERSION }}
      - name: Retag latest
        run: docker tag perihub/backend:${{ steps.get_version.outputs.PERIHUB_VERSION }} perihub/backend:latest
      - name: Retag latest
        run: docker tag perihub/frontend:${{ steps.get_version.outputs.PERIHUB_VERSION }} perihub/frontend:latest
      - name: Publish to Registry
        run: docker push perihub/backend:latest
      - name: Publish to Registry
        run: docker push perihub/frontend:latest
